<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vietnam</name>
   <tag></tag>
   <elementGuidId>17fed75d-05fe-4036-adab-dc62a23c4dee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='f_4ce04ce3-9f31-4492-992a-b4c6b057bd78_237']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#f_4ce04ce3-9f31-4492-992a-b4c6b057bd78_237 > div.q-item__section.column.q-item__section--main.justify-center > div.q-item__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>424d0a82-73e7-44f3-afba-8a8a1afa5318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>q-item__label</value>
      <webElementGuid>88a6ad7f-c526-4303-8698-5347a6a4dedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vietnam</value>
      <webElementGuid>b016a1f9-dd99-4470-b6c3-d8478b558843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f_4ce04ce3-9f31-4492-992a-b4c6b057bd78_237&quot;)/div[@class=&quot;q-item__section column q-item__section--main justify-center&quot;]/div[@class=&quot;q-item__label&quot;]</value>
      <webElementGuid>fd9c8b4c-0f9f-4a76-86ae-1a1f6c70f2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f_4ce04ce3-9f31-4492-992a-b4c6b057bd78_237']/div[2]/div</value>
      <webElementGuid>2972885d-b2cb-4845-bd68-aa682db4335f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venezuela (Bolivarian Republic of)'])[1]/following::div[4]</value>
      <webElementGuid>85399ec2-20f5-4fd6-8e00-d2eb750b9aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vanuatu'])[1]/following::div[8]</value>
      <webElementGuid>6e9829f5-92c2-42bd-ac80-8f8a4affbc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallis and Futuna Islands'])[1]/preceding::div[2]</value>
      <webElementGuid>d0973291-71d7-4977-a0d5-0c6a458ee1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Western Sahara'])[1]/preceding::div[6]</value>
      <webElementGuid>55812cb6-531f-48ab-b597-b28de1fd6db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div</value>
      <webElementGuid>21e30730-5fdb-4383-b0fe-55bb25f0f310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Vietnam' or . = 'Vietnam')]</value>
      <webElementGuid>185d1e35-37b1-49ef-8ea3-e11874aa4e7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
