<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemGender</name>
   <tag></tag>
   <elementGuidId>6e05e449-630f-493e-8952-c77c58c36eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='q-virtual-scroll__content']//div[text()='Male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='q-virtual-scroll__content']//div[text()='Male']</value>
      <webElementGuid>7391ea3a-08f5-4eb0-9355-67b4990ea7e7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
