<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemLanguageProfi</name>
   <tag></tag>
   <elementGuidId>f56deb95-cd5a-40db-bc5c-a8124888feac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='q-virtual-scroll__content']//div[text()='Business']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='q-virtual-scroll__content']//div[text()='Business']</value>
      <webElementGuid>8908f619-0954-4a11-9e17-3608f7198f01</webElementGuid>
   </webElementProperties>
</WebElementEntity>
