<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>itemCitizenship</name>
   <tag></tag>
   <elementGuidId>bbd12646-6e48-459d-a33f-c2f14afa656d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='q-virtual-scroll__content']//div[text()='Albania']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='q-virtual-scroll__content']//div[text()='Albania']</value>
      <webElementGuid>b319451b-986a-45ed-860a-2e5c0bfbdc68</webElementGuid>
   </webElementProperties>
</WebElementEntity>
