<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAgree</name>
   <tag></tag>
   <elementGuidId>55e29cb1-7f40-4c2c-bb56-5cc220ae46a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='AgreeToTermsAndConditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='AgreeToTermsAndConditions']</value>
      <webElementGuid>e3782b16-434b-45bd-9c36-7ca50b44851f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
