<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailErr</name>
   <tag></tag>
   <elementGuidId>4e31fd8b-bc18-4d1c-8997-40561ae3b9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='Email-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='Email-error']</value>
      <webElementGuid>19dbe3e6-3291-4674-aa3e-af58379f21db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
