<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelHello</name>
   <tag></tag>
   <elementGuidId>bf72da00-26ed-44b2-96d5-b87c4dd044bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@automation-id='candidateName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@automation-id='candidateName']</value>
      <webElementGuid>318a6a83-f375-4c4e-99e1-3a472e22a64f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
