<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputOldPassword</name>
   <tag></tag>
   <elementGuidId>000c9354-ced7-41ed-84f2-da970fb93795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='OldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='OldPassword']</value>
      <webElementGuid>e350eb62-5a05-47fd-8ffa-766a9314a361</webElementGuid>
   </webElementProperties>
</WebElementEntity>
