<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCamera</name>
   <tag></tag>
   <elementGuidId>de29ad91-443c-4250-91f9-88aa493ddaff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[text()='camera_alt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[text()='camera_alt']</value>
      <webElementGuid>2fc9af41-fdc5-4828-aedd-d5f6c8b31930</webElementGuid>
   </webElementProperties>
</WebElementEntity>
